// <auto-generated />
using Cityinfo.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cityinfo.API.Migrations
{
    [DbContext(typeof(cityInfoContext))]
    [Migration("20260411074217_InitialDataSeed")]
    partial class InitialDataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Cityinfo.API.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Hogenakkal Falls",
                            Name = "Dharmapuri"
                        },
                        new
                        {
                            Id = 2,
                            Description = "House of the seven Gables",
                            Name = "Salem"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Handloom textiles",
                            Name = "Erode"
                        });
                });

            modelBuilder.Entity("Cityinfo.API.Entities.pointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("pointOfInterests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "It blends hill heritage with a calm elevation walk",
                            Name = "Theerthamalai Temple"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Description = "Carrying the district’s medieval stone-defense identity",
                            Name = "Adhiyamankottai Fort"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Description = "Tourist Place",
                            Name = "Yercaud"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Description = "One of the most famous place",
                            Name = "Mettur Dam"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 3,
                            Description = "Devotional Place",
                            Name = "Thindal Murugan Temple"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 3,
                            Description = "Sanctuary with boat riding",
                            Name = "Vellode Bird Sanctuary"
                        });
                });

            modelBuilder.Entity("Cityinfo.API.Entities.pointOfInterest", b =>
                {
                    b.HasOne("Cityinfo.API.Entities.City", "City")
                        .WithMany("pointOfInterests")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Cityinfo.API.Entities.City", b =>
                {
                    b.Navigation("pointOfInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
